EXTRA_CFLAGS += -Ilib/lunatik/lua/include 

obj-y += lapi.o lcode.o ldebug.o ldo.o ldump.o lfunc.o lgc.o llex.o lmem.o \
         lobject.o lopcodes.o lparser.o lstate.o lstring.o ltable.o ltm.o  \
         lundump.o lvm.o lzio.o lauxlib.o 

