EXTRA_CFLAGS += -Ilib/lunatik/lua/include 

obj-$(CONFIG_LUNATIK_PRINTK) += lunatik_printk.o
lunatik_printk-objs := printk.o

obj-$(CONFIG_LUNATIK_INSPECT) += lunatik_inspect.o
lunatik_inspect-objs := inspect.o

obj-$(CONFIG_LUNATIK_CRYPTO) += lunatik_crypto.o
lunatik_crypto-objs := crypto.o

obj-$(CONFIG_LUNATIK_BUFFER) += lunatik_buffer.o
lunatik_buffer-objs := buffer.o
