#!/bin/sh

echo "/* autogenerated list of to be exported functions from lua */"

HEADERS=
OBJECTS=

for F; do
	echo File: "$F" >> ~/lunatik-build.log
	case $F in
	*.h)
		HEADERS="$HEADERS $F"
		;;
	*.o)
		OBJECTS="$OBJECTS $F"
		;;
	esac
done

for H in $HEADERS; do
	if [ $H != luaconf.h ]; then
		echo
		echo "#include \"${H##*/}\""
		grep -e '\(LUA_API\|LUALIB_API\|LUAI_FUNC\)' $H |
			sed 's/([^(]*$//' |
			sed 's/[()*]//g' |
			awk '{print $NF}' |
			sort |
			while read S; do
				for O in $OBJECTS; do
					if nm $O | grep -q -w $S; then
						echo "EXPORT_SYMBOL($S);"
						break
					fi
				done
			done
	fi
done
